### ISSUE TITLE
I get the following issue when trying to build 

### ISSUE THREAD

**Issue by joshash** [codelucas/newspaper#212]
my code is:
```
from newspaper import Article 
import newspaper

cnn_paper = newspaper.build('http://cnn.com')
```

And I get the following error:
`unable to cache TLDs in file /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tldextract-1.5.1-py3.5.egg/tldextract/.tld_set: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tldextract-1.5.1-py3.5.egg/tldextract/.tld_set'`

**Comment by yprez** [comment]
Seems like a problem with permissions. I think that if you install in a virtualenv and not as root, you won't have this problem.

It has to do with tldextract caching urls in it's installation path, which in your case you don't have permissions for.

https://github.com/john-kurkowski/tldextract/blob/158c1104fe0081754f45743c2f8f91c0096bb672/README.md#note-about-caching--advanced-usage

This can be fixed in newspaper (by passing a different cache file, or disabling cache) or in tldextract itself.

**Comment by yprez** [comment]
@joshash 
For now, you can fix this by installing in a virtualenv, or setting the `TLDEXTRACT_CACHE` environment variable to somewhere writable, e.g. `export TLDEXTRACT_CACHE=~/tldextract.cache`

**Comment by joshash** [comment]
Hi,

How exactly do I do that? I'm a total programming beginner. In which file
would I set the  TLDEXTRACT_CACHE environment variable to export
TLDEXTRACT_CACHE=~/tldextract.cache  ?

**Comment by joshash** [comment]
Ie, when I open the TLDEXTRACT.py file, I changed it so I have CACHE_FILE =
os.path.expanduser(os.environ.get("TLDEXTRACT_CACHE", "export
TLDEXTRACT_CACHE=~/tldextract.cache")) , but now I when I try to build the
newspaper I get:

 unable to cache TLDs in file export TLDEXTRACT_CACHE=~/tldextract.cache:
[Errno 2] No such file or directory: 'export
TLDEXTRACT_CACHE=~/tldextract.cache'

**Comment by yprez** [comment]
@joshash sorry, I meant running it in the shell before running the python script.

In python that would be:

```
import os
os.environ['TLDEXTRACT_CACHE'] = '~/tldextract.cache'
```

If you add it before importing newspaper, I think it should work...

**Comment by joshash** [comment]
Hi Yuri,

That worked. Thanks for the awesome library/help!
