### ISSUE TITLE
Where does "google_sources.txt" come from?

### ISSUE THREAD

**Issue by yuhonglin** [codelucas/newspaper#253]
Hi,

First, thank all the contributors, especially the owner of this project, for the excellent work! I have a quick question, how does the file "google_sources" come from? (the file is "https://github.com/codelucas/newspaper/blob/master/newspaper/resources/misc/google_sources.txt) And how about the popular sources? Can these be documented?

Thanks again!

Regards,
Honglin

**Comment by yprez** [comment]
Looks like google news sources to me, but I don't know the exact source.
@codelucas would probably know...

**Comment by codelucas** [comment]
Hah I'm glad somebody brought this up. That text file should not have been in this repo!

While I was working on http://wintria.com (news startup) a few years ago we were interested in the domains of news companies other aggregators like google news / summly / flipboard scraped from -- **actually as a sanity check on how to improve newspaper!**

As it turns out, the list of domains that google news scraped from .. got leaked! In that text file

**Comment by codelucas** [comment]
Please close this @yuhonglin -- if you feel that explanation is sufficient

**Comment by yuhonglin** [comment]
@codelucas Thank you very much for the explanations! Actually I am a post-doc doing research on news medias. To define the scope of news media considered, we need a list like the "google_sources.txt" but must with an description to let us know how the data is biased. Now as you explained, this comes from the medias scraped by google --- this is a really good list and saves us lots of time! Thanks again!
