### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/newspaper/resources/misc/stopwords-nlp-en.txt'

### ISSUE THREAD

**Issue by andyforceno** [codelucas/newspaper#380]
I get the following error when trying to run a Python script that uses newspaper:

`IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/newspaper/resources/misc/stopwords-nlp-en.txt'`

I checked, and the resources folder is missing from that location. I tried re-installing newspaper, but I got the same error again.

**Comment by codelucas** [comment]
Good news! Problem has been found, I just pushed a new newspaper (python2) package to pip, please update now: `pip install newspaper==0.1.0.2`

The root cause was that 2 days ago i accidentally pushed a python2 newspaper binary without being in virutalenv (causing my setuptools import to be much much much older) which mis-interpreted MANIFEST.in causing all of the data files to be lost!

It works for me!

```
Successfully installed newspaper-0.1.0.2
(python2-newspaper-test) ------------------------------------------------------------
~VIRTUAL_ENV » python                                                                                                                                       l@mbp
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import newspaper
```

**Comment by andyforceno** [comment]
Yes, that fixed it, although I had to install install `libxml2-dev` and `libxslt1-dev` prior to running `pip install newspaper==0.1.0.2`. Thanks!
