### ISSUE TITLE
Limited number of urls

### ISSUE THREAD

**Issue by frank627** [codelucas/newspaper#505]
Hello. I'm trying to write a code to find url of NYT articles that involve certain word. 
Before I start writing code to check text in each website, I checked how many webpages that I can access by using Newspaper API and found out that the number is limited. 

Here is part of my code : 
import newspaper
nyt_paper = newspaper.build("http://www.nytimes.com",memoize_articles=False, language='en')
print(len(nyt_paper.articles))
---------
When I run this code, I always get 298.
Would there be any way to fix this problem?

**Comment by codelucas** [comment]
This is a known behavior, it is because newspaper is caching the # of urls for that domain locally, please see:

**Comment by codelucas** [comment]
Also see @yprez's answer here: https://github.com/codelucas/newspaper/issues/243#issuecomment-218248310

**Comment by frank627** [comment]
I already had "memoize_articles=False" part in my code. 

Would there be no way to search all articles from one newspaper website?

**Comment by Julia-Lovelace** [comment]
@frank627 It's been a long time since you asked so I wonder how that resolved for you.
If you wanted to search all the articles then caching would help you.  You would want to cache articles when you build and run the build command until the size of the new articles pulled in equals 0.  That is how I imagine solving it anyways.
