### ISSUE TITLE
You must download and parse an article before parsing it

### ISSUE THREAD

**Issue by bitliner** [codelucas/newspaper#52]
Here the stack trace:

```
[Parse lxml ERR] line 1045: Tag nav invalid
[Article parse ERR] http://www.cnet.com/products/apple-ipad-march-2012/
You must download and parse an article before parsing it!
Traceback (most recent call last):
  File "crawler.py", line 30, in <module>
    a.nlp()
  File "/root/.virtualenvs/cnet-crawler/local/lib/python2.7/site-packages/newspaper/article.py", line 276, in nlp
    raise ArticleException()
newspaper.article.ArticleException
```

I'm not using the concurrent version, I'm not building a newspaper from a url, but rather I have a list of all the articles and I build a new Article from them.

**Comment by Casyfill** [comment]
But how can I switch to bf parser? Can't find any documentation on that

**Comment by cesarandreslopez** [comment]
Same here. Not sure how to change the parsing to BeautifulSoup

**Comment by go2dmny** [comment]
Any update? Also looking for a solution

**Comment by sbv-csis** [comment]
Turns out most distributions of Linux don't have HTML5 capable libxml2 installed (often version 2.9.1) and and since libxml2 don't understand nav, header and other HTML5 tags, Lxml in turn don't understand it (if you are lucky and have 2.9.3+ all is well). Notably, Amazon Linux AMI used for aws Lambda has 2.9.1. Anyone got good workarounds? The beautiful soup workaround sounds promising @codelucas but I cant find the way to change it. Implement a new Parser in parsers.py and change via config?
