### ISSUE TITLE
Error while webscraping multiple websites

### ISSUE THREAD

**Issue by shuggiebain** [codelucas/newspaper#613]
Error:  Article `download()` failed with 404 Client Error: Not Found for url: https://www.nytimes.com/reuters/2017/08/05/business/05reuters-britain-eu-king.html on URL https://www.nytimes.com/reuters/2017/08/05/business/05reuters-britain-eu-king.html
```
content = []
for i in test.url:
    article = Article(str(i))
    try:
        article.download()
        article.parse()
        article.download()
        article.html
        article.parse()
        text = article.text
        content.append(text)
    except:
        content.append('error')
    continue
```

Error:

**Comment by Kiedi7** [comment]
Code:
```
content = []
for i in test.url:
article = Article(str(i))
try:
article.download()
article.parse()
article.download()
article.html
article.parse()
text = article.text
content.append(text)
except:
content.append('error')
continue
```

**Comment by Kiedi7** [comment]
How can I use exception handling in the loop to ignore this?

**Comment by iwpnd** [comment]
First off, you don't have to download/parse the article twice. Check the documentation for the proper use.

```python
(...)
except:
    pass
```

This would ignore the error and would continue the loop without handling the exception.

```python
(...)
except yourError as e:
    content.append(e)
```

This would catch the error (see error msg for exact one) in a variable and append it to ``content``. Continue is not necessary because you properly handle the exception (and would have to be properly intended anyways).
