### ISSUE TITLE
Port to Ruby

### ISSUE THREAD

**Issue by thejourneydude** [codelucas/newspaper#8]
It would be lovely if I could port this to Ruby. I think one issue I'll have to deal with is replacing Beautiful Soup with Nokogiri. I need to sit down and go through all of the code to spot any issues that may arise.

**Comment by rcavezza** [comment]
@thejourneydude @codelucas Did this ever get ported to ruby?

**Comment by thejourneydude** [comment]
No, unfortunately not. Nor do I think there are plans to do so. If you want to go ahead and pursue this monumental task, by all means. I don't think @codelucas would have any problem with that. Right Lucas?

**Comment by codelucas** [comment]
It's a tough task! I think one reason why it never happened is because Ruby/Python are similar languages in terms of things like runtime / abstraction.

If a need existed for this to run super fast, maybe porting it to something lower level (c++) would be helpful? It's up to you @rcavezza @thejourneydude
