### ISSUE TITLE
Scraping pages with infinite scrolling

### ISSUE THREAD

**Issue by monilouise** [codelucas/newspaper#890]
Hi,

Is there any workaround to identify or suspend web scraping for pages with infinite scrolling?  Here's a sample code:

from newspaper import Article

article = Article('https://www.blogdomontoril.com.br/blog/busca.php')
article.download(recursion_counter=1)
article.parse()

**Comment by johnbumgarner** [comment]
infinite scrolling requires you to use the module [selenium](https://www.selenium.dev/downloads/) which is outside the capabilities of Newspaper. 

Also the source that you are scraping also requires other coding beyond selenium and/or Newspaper. 

 I would recommend reviewing my [newspaper overview document](https://github.com/johnbumgarner/newspaper3_usage_overview).  If you are still have issues after looking through the document then I would recommend opening a question on Stack Overflow under the tags _python-newspaper_ and _newspaper3k_.  

Also please close this issue, because it isn't related to Newspaper per se.

**Comment by monilouise** [comment]
Issue not relates no Newspaper.
