### ISSUE TITLE
Can I get the CSS Selectors ?

### ISSUE THREAD

**Issue by izJoey** [codelucas/newspaper#977]
Hi, there is a way to get the CSS selectors in the articles founded? 
Like article title, text, and date.

I tried so hard and no success.

**Comment by AndyTheFactory** [comment]
Hi, 
for the article text you can use the article.top_node to see where it got it's text. 

unfortunatelly for title and date the way it detected them is not passed on to the user.

btw, i have forked the project (since this one is no longer maintained) and you can use it as a less buggier version of newspaper3k - https://github.com/AndyTheFactory/newspaper4k 
or 
     `pip install newspaper4k `

**Comment by izJoey** [comment]
Thx for the help! 

Oh, you did a good work there.
